CREATE DATABASE Mvc;

use Mvc;

CREATE TABLE UTILISATEUR (
user_id INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
nom VARCHAR(60) NOT NULL , 
prenom VARCHAR(60) NOT NULL
);

CREATE TABLE Telecharge (
user_id INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
doc_id INT(11) ,
date DATE NOT NULL
);

CREATE TABLE Document(
doc_id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
doc_titre VARCHAR(60) NOT NULL

);

